### ISSUE TITLE
Add configuration for backend sections

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#1519]
As commented in https://github.com/MetaModels/boilerplate/issues/1#issuecomment-2575757390, we want some configuration options to add custom sections in the backend.

```yaml
be_sections:
    products:
        name:
            de: 'Produkte'
            en: 'Products'
        tooltip:
            de: 'Produkte erstellen'
            en: 'Create products'
        icon: 'file/theme/mm/products.svg'
        add:
            before: layout
```

We might need more options here (like initial collapsed etc).
