### ISSUE TITLE
BE: Translate Auswahl im Safari defekt

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#169]
Im Safari (  Version 6.0.4 (8536.29.13) ) ist das select zur Sprachauswahl verrutscht. 
Die Auswahl kann aber an der vermuteten Stelle erfolgen.

Folgendes css fixed das Problem, ich weiß aber nicht ob sich das sinnvoll ist so zu lösen.

``` css
.tl_formbody {
position:relative;
}

.styled_selected {
right: 110px;
top: 3px; }
```

![bildschirmfoto 2013-05-29 um 13 12 14](https://f.cloud.github.com/assets/1793396/578291/edad6d9a-c850-11e2-9b69-76af65d3c839.png)
![bildschirmfoto 2013-05-29 um 13 12 06](https://f.cloud.github.com/assets/1793396/578292/edc2607e-c850-11e2-89b5-f08210fed08f.png)
