### ISSUE TITLE
usability beim Input-panel

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#861]
![model_list_panel](https://cloud.githubusercontent.com/assets/4138336/9240296/c1e7db0c-4164-11e5-9a22-c8f7af9717e0.png)
* 1. Filter hat hat automatisch leere Option selektiert sobald das entsprechende Feld bei irgendeinem Datensatz leer ist - sollte aber die Feldbezeichnung anzeigen.
* 2. Suchen bietet alle sichtbaren Felder der Eingabemaske zur Auswahl - sollte aber nur die Felder zeigen, die als durchsuchbar markiert sind.
* 3. Limit springt bei der Auswahl von "Alle" auf "1-30" zurück (listet aber alle Datensätze)
Pagination am Seitenende wie im contao/core wäre in diesem Zusammenhang auch nice to have

**Comment by asaage** [comment]
zu Punkt 3:
reopen contao-community-alliance/dc-general#70

**Comment by Hoch-3** [comment]
Punkt 1 ist bei mir in der Version vom 13.8. so wie von asaage geschildert. Unschön.
Punkt 2 gibt bei mir noch ein anderes Problem. Wenn nach einem Feld weiter hinten gesucht wird, zeigt es nach der Suche immer das oberste Feld an, allerdings mit rechts davon dem Suchbegriff des anderen Feldes.
Dann noch ein 4. Punkt:
Schön wäre ein Reset-Knopf von sämtlichen zwischengespeicherten Filtern oder Suchen.

**Comment by Aybee** [comment]
Sofort reagierende Select-Felder und einen Reset-Button, das hatte ich mir mal aufgemotzt und finde es sehr praktisch. Am besten im System-Log testen.
```javascript
/**
 * files/js/_my_be.js
 */

(function($) {
  window.addEvent('domready', function() {

    // Immediatly reload page after filter select or sort select
    $$('.tl_filter select, .tl_sorting select').addEvent('change', function() {
      this.form.submit();
    });



    // Create a reset button to reset the panel selects and submit
    var submitPanel = $$('.tl_submit_panel') || false;

    if(submitPanel[0]){
      var
        resetButton,
        resetSelects = $$('.tl_filter select, .tl_limit select'),
        searchText = $$('input[type=search]')
      ;

      // create the reset button
      resetButton = new Element('div.reset_button', {
        title: 'Filter, Suche und Limit zurücksetzen - dann neu laden'
      });

      resetButton.addEvent('click', function() {
        Array.each(resetSelects, function(el) {
          el.getSelected().setProperty('selected', '');
        });
        searchText.erase('value');
        submitPanel[0].getParent('form').submit();
      });

      resetButton.inject(submitPanel[0]);
    }

  });
})(document.id);
```
```css
/**
 * files/css/_my_be.css
 */
.tl_panel {
  position: relative;
  text-align: left;
}
.tl_subpanel {
  float: none;
  display: inline-block;
  padding-left: 6px;
}
.tl_submit_panel {
  float: right;
}
.tl_submit_panel .tl_img_submit {
  width: 23px;
  top: auto;
}
.reset_button {
  width: 23px;
  height: 23px;
  background-image: url(../../system/themes/default/images/reload.gif);
  filter: hue-rotate(45deg);
  background-size: cover;
  display: inline-block;
  cursor: pointer;
}
```
Kann man zum Testen z.B. über die system/config/initconfig.php ins BE bringen.
```php
<?php
/**
 * system/config/initconfig.php
 */

/**
 * Here you can add custom initialization routines that are executed
 * on every back end and front end request.
 */

/** Some extra BE CSS and JS */
if(TL_MODE == 'BE')
{
  $GLOBALS['TL_CSS'][]        = 'files/css/_my_be.css';
  $GLOBALS['TL_JAVASCRIPT'][] = 'files/js/_my_be.js';
}
```
